# extensions for twig templating engine
twig-extensions:
  - TwStats\Ext\TwigExtension\SlugifyUrl
includeCss:
  - /assets/twstats/vendor/font-awesome/css/font-awesome.min.css
  - /assets/twstats/vendor/bootstrap/css/bootstrap.min.css
  - /assets/twstats/public/css/bundle/bundle.min.css
includeJsHead:
  - /assets/twstats/vendor/jquery/jquery.min.js
includeJs:
  - /assets/twstats/vendor/popper.js/umd/popper.min.js
  - /assets/twstats/vendor/bootstrap/js/bootstrap.min.js
  - /assets/twstats/vendor/jquery.cookie/jquery.cookie.js
  - /assets/twstats/vendor/chart.js/Chart.min.js
  - /assets/twstats/vendor/jquery-validation/jquery.validate.min.js
  - /assets/twstats/public/js/bundle/bundle.js
defaultTemplate: default.twig
cache: false
compress-html: false