# extensions for twig templating engine
twig-extensions:
  - TwStats\Ext\TwigExtension\SlugifyUrl
includeCss:
  - /assets/twstats/public/css/bundle/bundle.min.css
includeJs:
#  - /assets/twstats/public/js/bundle/bundle.js
defaultTemplate: default.twig
cache: false
compress-html: true