version: '3.7'

services:
  app:
    image: webdevops/php-apache-dev:7.2
    container_name: tw-stats.local
    # undocumented, on failure it tries to restart 5 times
    restart: on-failure:5
    networks:
    - app_network
    privileged: true
    volumes:
    - ./../:/app
    env_file:
    - ./environment/app.env
    environment:
    - VIRTUAL_HOST=tw-stats.local
    - VIRTUAL_PROTO=http
    - HTTPS_METHOD=noredirect
    - WEB_DOCUMENT_ROOT=/app/public/

networks:
  # network already got built by the DockerVM docker-compose.yml
  app_network:
    external: true
    name: app