name: Composer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: sockets, json, pdo_sqlite
          coverage: none
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: vendor/bin/phpunit
